// <auto-generated />
using System;
using HRM.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRM.Infra.Data.Migrations
{
    [DbContext(typeof(HRMContext))]
    [Migration("20190613110536_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRM.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(11);

                    b.Property<DateTime>("Modified");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRM.Domain.Employee", b =>
                {
                    b.OwnsOne("HRM.Domain.Models.Person", "Person", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId");

                            b1.Property<DateTime>("Dob")
                                .HasColumnName("Dob");

                            b1.Property<string>("FirstName")
                                .HasColumnName("FirstName");

                            b1.Property<int>("Gender")
                                .HasColumnName("Gender");

                            b1.Property<string>("LastName")
                                .HasColumnName("LastName");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.HasOne("HRM.Domain.Employee")
                                .WithOne("Person")
                                .HasForeignKey("HRM.Domain.Models.Person", "EmployeeId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("HRM.Domain.SharedKernel.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId");

                            b1.Property<string>("City")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .HasColumnName("Country");

                            b1.Property<string>("State")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .HasColumnName("Street");

                            b1.Property<string>("ZipCode")
                                .HasColumnName("ZipCode");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.HasOne("HRM.Domain.Employee")
                                .WithOne("Address")
                                .HasForeignKey("HRM.Domain.SharedKernel.Address", "EmployeeId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
